http://localhost:4000/
###
http://localhost:4000/blocks
###
http://localhost:4000/blocks/c2009dee3d84835da1376d49df13d757f5a4eeeb4826bb1d94024e65744a0855
###
POST http://localhost:4000/blocks

{
    "message": "Data for my block (5)"
}
###
GET http://localhost:4000/blocks/3